language: node_js
node_js:
- lts/*
script:
- yarn build
deploy:
- provider: script
  skip_cleanup: true
  script:
  - npx --package @dhis2/deploy-build deploy-build
  on:
    tags: false
    all_branches: true
env:
  global:
    secure: NxchU0mm5nbtoLSeugUsvGoibo+0OPSFmcv7Tz7PkS43d01HSCo04naIb9F99Skn75a7Dqs5xLpJq1d0K8ZOeY1mGR7onOP26YsUGbQt5dC42wtLg2d5o0IugDAW9tXXAtL1JASv/Wd0WK1Klz9tiM5bwe6xmwhctxvPhgH5D9uedq4cjdq+Jd6OG1SZcQvd6LlPH4wu3mT1lQlv56lSGreJRPYJFEYK9ZLsnolB5JyRg8UjYhIjdtdzekJYHyAbhhbcAO6pW+61jGsnYdhsyiVTwjr6AZyrQI/iOKupcS5EkYL+Z7gAH16viGlnkKXPz8AGqyMfFaMb9ZDv7Mqvme3VmpnSR4Kt2+t1odv6vPM5RsS++DBuiPkVYv2ib/mIbCQwYLLFDcPgZCiwdfHU7CdBDwuvm0nMChbzczoNIXHdRJYN3KtBro6iCaKgcNHkWen5n9c0OHP0g89+BgUhqL+gWzLLHiQJFOwag61ycM6n2WgfHy4qbST2M2BOevR2qfg/SU+qT5YduKudpKaahv1if/Mih/nV6SjjDmluYdJXjoiv3JJnceOeFcKBkBpInDvZegj4uy92y9Ovo5M1Xz+s4hydnzWhgjc/A7Tnw8SpIwFJtlIj2eZrovnky9KWFU6TaE+L7+al9ZwG9Caufxfv3MQWeQ7y67r5m+7RLNo=
